inference:
  batch_size: 4
  num_workers: 0 # Windows optimization
  tta_shifts: [0, -1, 1] 
  tile_size: 256
  stride: 192
  threshold: 0.50
  mixed_precision: true
  
model:
  name: MiniUNETR
  args:
    in_channels: 1
    out_channels: 1
    img_size: 256
    patch_size: 16
    hidden_size: 256
    num_heads: 8
    feature_size: 16

data:
  base_path: data/vesuvius-challenge-ink-detection
  z_start: 4
  z_end: 21
